### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ghost**
I believe python-dateutil is also a requirement.  At least I needed to install it in order to run git2net 
Jose Teixeira, Åbo Akademi, Turku

Please consider to merge

### CODE REVIEW

**Comment by gotec** [comment]
Hi Jose,
thanks for your message! Can you let me know for which function you required `dateutil` and which OS you are running? I just double-checked and from what I can tell I only require `datetime`, which should be built in to any *python3* environment.
Cheers,
Christoph

**Comment by ghost** [comment]
Hi

I was using a standard Debian image from osboxes.org. I needed to install
that package when running 'pip3 install git2net'. I have other Linux
machines, I will try to reproduce this issue and let you know.

Meeting today 17:00? Or it is more convenient later this week?
Jose

**Comment by gotec** [comment]
Thanks for double-checking that. I'll be there at 17:00.

**Comment by gotec** [comment]
Closed as issue could not be replicated.

**Pull request closed without merging**
